### ISSUE TITLE
TypeError: 'KeysView' object does not support indexing

### ISSUE THREAD

**Issue by vinaysworld** [KaiyangZhou/vsumm-reinforce#3]
Hi, Can you help me in this line, what modification should i do?
Traceback (most recent call last):
  File "vsum_train.py", line 155, in <module>
    train_dataset_path=args.dataset)
  File "vsum_train.py", line 83, in train
    key = dataset_keys[index]
TypeError: 'KeysView' object does not support indexing

**Comment by KaiyangZhou** [comment]
Hi,
I think you are using python3 so dictionary.keys() could not be indexed. What you can do is to replace line63 by
```python
#dataset_keys = dataset.keys()
dataset_keys = list(dataset.keys())
```
Thanks for spotting this. I have updated this in the scripts.

**Comment by vinaysworld** [comment]
Hi,
I have completed all the process and got the log file which saying final outcome. but as i studied in your paper, you had used video 18 in TVSum dataset for generating summary or importance score, can i also  do this. 
As I am student and new one in neural networks, can you give the way, how I will give the video as input and got the important frames or summarized frames, and all the necessary graphs. 
Thank you

**Comment by KaiyangZhou** [comment]
If you want to get the raw output of the summarization network (i.e. importance scores, Fig.3 in our paper), you would need to save the output of `probs = net.model_inference(data_x)` in [this line](https://github.com/KaiyangZhou/vsumm-reinforce/blob/master/vsum_test.py#L76) (e.g. to a new h5 file).

To get the summarized frames (Fig.2 in our paper), you can save `machine_summary = vsum_tools.generate_summary(probs, cps, n_frames, nfps, positions)` ([this line](https://github.com/KaiyangZhou/vsumm-reinforce/blob/master/vsum_test.py#L83)). `machine_summary` is a binary vector indicating which frames are included in the summary.

Hope this would help.

**Comment by AdarshMJ** [comment]
Im not sure I understand when you said save machine_summary = vsum_tools.generate_summary(probs, cps, n_frames, nfps, positions).

Is there a provision to give one video file as input via command line? Could you please elaborate this


To get the summarized frames (Fig.2 in our paper), you can save machine_summary = vsum_tools.generate_summary(probs, cps, n_frames, nfps, positions) (this line). machine_summary is a binary vector indicating which frames are included in the summary.

**Comment by KaiyangZhou** [comment]
@AdarshMJ 
For example, the input video has 5 frames, `machine_summary = [0, 0, 1, 1, 0]` where positions with value 1 mean these frames are keyframes (summary). You need to manually pick those frames (in this example, frame3 and frame4).

**Comment by AdarshMJ** [comment]
Thank you so much. I got it. I wanted to know whether those indices actually represent the frame numbers or they are just indices?

**Comment by KaiyangZhou** [comment]
@AdarshMJ 
The values represent whether the frames are selected. To find those indices, you can do sth like `summary.nonzero()`. I have just updated the code to include the visualization tool, so you can visualize the score-vs-gtscore.

**Comment by AdarshMJ** [comment]
Thank you so much. I will check out. I wanted to know how to create the h5 file for my own dataset? I checked out the links and readme.txt. But there are so many parameters that has to be included for the h5 file to be created, like gt scores and all that. is it possible to update your code for generating this data? That would be helpful.

**Comment by KaiyangZhou** [comment]
It might be unnecessary to do this because the way you generate the image features and ground truth score/summary would be different and dependent on your purpose. You can follow [this](https://github.com/KaiyangZhou/vsumm-reinforce/issues/1#issuecomment-363492711) after you got those data.

**Comment by KaiyangZhou** [comment]
If you just wanna train policy network, you will need features only. Pls double check the `vsum_train`

**Comment by AdarshMJ** [comment]
I checked out your vsum_train.py code. In these lines 


        for index in indices:
            key = dataset_keys[index]
            data_x = dataset[key]['features'][...].astype(_DTYPE)
            L_distance_mat = cdist(data_x, data_x, 'euclidean')
            L_dissim_mat = 1 - np.dot(data_x, data_x.T)
            if ignore_distant_sim:
                inds = np.arange(data_x.shape[0])[:,None]
                inds_dist = cdist(inds, inds, 'minkowski', 1)
                L_dissim_mat[inds_dist > distant_sim_thre] = 1
            rewards = net.model_train(data_x, learn_rate, L_dissim_mat, L_distance_mat, blrwds[key])
            blrwds[key] = 0.9 * blrwds[key] + 0.1 * rewards.mean()
            epoch_reward += rewards.mean()



This means the training is done using only the features which have been extracted from the videos right? It is not taking into account the rest of the parameters like gtscore, user_summary and all that?

**Comment by KaiyangZhou** [comment]
@AdarshMJ 
Yes, only the features are needed for training.
