### ISSUE TITLE
Video Testing

### ISSUE THREAD

**Issue by ab-bh** [KaiyangZhou/vsumm-reinforce#5]
How can we test the model on actual videos to see how the summarized output is ?
Apart from the h5 model files given in the readme file.

**Comment by KaiyangZhou** [comment]
To get the summary, please refer to [here](https://github.com/KaiyangZhou/vsumm-reinforce/issues/3#issuecomment-375602006).
You need to preprocess the videos that you want to summarize, i.e. extract features and save them in h5 file. Hope this would help.

**Comment by vinaysworld** [comment]
Hi
Can you give us a demo code of full process for generating summarised frames for a single video,
It will help to understand the whole process.
