### ISSUE TITLE
Demo for single Video

### ISSUE THREAD

**Issue by vinaysworld** [KaiyangZhou/vsumm-reinforce#6]
Hi
Can you give us a demo code of full process for generating summarised frames for a single video,
It will help to understand the whole process.

**Comment by KaiyangZhou** [comment]
There is no code for this process.

To retrieve the summarised frames, you need `machine_summary` from [here](https://github.com/KaiyangZhou/vsumm-reinforce/blob/master/vsum_test.py#L83). `machine_summary` is a binary vector with length equal to the number of frames, so it is intuitive to get the summarised frames by manually picking those frames with values equal to 1. Hope this is clear.

**Comment by vinaysworld** [comment]
Hi, how to save this machine summary, means what syntax we have to use

**Comment by KaiyangZhou** [comment]
You can use h5 file to save it.

```python
import h5py

file = h5py.File('path_to_dir/results.h5', 'w')
for video_i in videos:
    machine_summary = compute_summary()
    file.create_dataset('video_i/machine_summary', data=machine_summary)
file.close()
```

To read the file, do
```python
file = h5py.File('path_to_dir/results.h5', 'r')
summary = file['video_i/machine_summary'][...]
```
