### ISSUE TITLE
Where to visualise the summaries generated?

### ISSUE THREAD

**Issue by AdarshMJ** [KaiyangZhou/vsumm-reinforce#8]
I was successful in running the code thanks to your instructions. After running the test code, the output I get is this 
<img width="567" alt="screen shot 2018-04-21 at 10 12 24 am" src="https://user-images.githubusercontent.com/24205200/39080460-b741e5b4-454c-11e8-84ec-1ae654556c7d.png">

Where can I visualise the summaries generated?

**Comment by KaiyangZhou** [comment]
Please refer to [this answer](https://github.com/KaiyangZhou/vsumm-reinforce/issues/3#issuecomment-375602006). Let me know if you have further questions.
